# Generated by Django 5.1.1 on 2024-10-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_usersettings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="mute_sounds",
            field=models.BooleanField(default=False),
        ),
    ]
