# Generated by Django 5.1.2 on 2024-10-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersettings_start_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='start_page',
            field=models.CharField(choices=[('MONTHLY_OVERVIEW', 'Monthly Overview'), ('YEARLY_OVERVIEW', 'Yearly Overview'), ('NETWORTH', 'Net Worth')], default='MONTHLY_OVERVIEW', max_length=255, verbose_name='Start page'),
        ),
    ]
