# Generated by Django 5.1.5 on 2025-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usersettings_start_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='date_format',
            field=models.CharField(default='SHORT_DATE_FORMAT', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='datetime_format',
            field=models.CharField(default='SHORT_DATETIME_FORMAT', max_length=100),
        ),
    ]
