# Generated by Django 5.1.5 on 2025-01-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usersettings_date_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='date_format',
            field=models.CharField(default='SHORT_DATE_FORMAT', max_length=100, verbose_name='Date Format'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='datetime_format',
            field=models.CharField(default='SHORT_DATETIME_FORMAT', max_length=100, verbose_name='Datetime Format'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto'), ('en', 'English'), ('nl', 'Nederlands'), ('pt-br', 'Português (Brasil)')], default='auto', max_length=10, verbose_name='Language'),
        ),
    ]
