# Generated by Django 5.1.5 on 2025-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_usersettings_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='number_format',
            field=models.CharField(default='AA', max_length=2, verbose_name='Number Format'),
        ),
    ]
