# Generated by Django 5.2.16 on 2026-09-12 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_usersettings_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='volume',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Volume'),
        ),
    ]
