# Generated by Django 5.1.1 on 2024-10-04 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("currencies", "0004_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="exchange_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Default currency for exchange calculations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exchange_accounts",
                to="currencies.currency",
                verbose_name="Exchange Currency",
            ),
        ),
    ]
