# Generated by Django 5.1.2 on 2024-10-08 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountgroup_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accountgroup', verbose_name='Account Group'),
        ),
    ]
