# Generated by Django 5.1.2 on 2024-10-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='archived',
            field=models.BooleanField(default=False, help_text="Archived accounts don't show up nor count towards your net worth", verbose_name='Archived'),
        ),
    ]
