# Generated by Django 5.1.6 on 2025-03-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_managers_alter_accountgroup_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
