# Generated by Django 5.2.9 on 2026-02-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_untracked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use as a default account when adding new transactions', verbose_name='Default'),
        ),
    ]
