# Generated by Django 5.1.1 on 2024-09-19 02:11

import apps.transactions.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('reference_date', apps.transactions.fields.MonthYearField(help_text='Please enter a month and year in the format MM/YYYY.')),
                ('description', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
