# Generated by Django 5.1.1 on 2024-09-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Transaction Tags',
                'verbose_name_plural': 'Transaction Tags',
                'db_table': 'tags',
            },
        ),
        migrations.AlterModelTable(
            name='transactioncategory',
            table='t_categories',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(to='transactions.transactiontags', verbose_name='Tags'),
        ),
    ]
