# Generated by Django 5.1.1 on 2024-09-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transactiontags_alter_transactioncategory_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionTags',
            new_name='TransactionTag',
        ),
    ]
