# Generated by Django 5.1.1 on 2024-09-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_transactiontags_transactiontag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transactions.transactiontag', verbose_name='Tags'),
        ),
    ]
