# Generated by Django 5.1.1 on 2024-10-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_installmentplan_transaction_installment_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="installmentplan",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="installmentplan",
            name="total_amount",
        ),
    ]
