# Generated by Django 5.1.1 on 2024-10-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_remove_installmentplan_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.transactioncategory",
                verbose_name="Category",
            ),
        ),
    ]
