# Generated by Django 5.1.1 on 2024-10-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0012_alter_transaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncategory",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="transactiontag",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
