# Generated by Django 5.1.2 on 2024-10-15 04:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transactioncategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactioncategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='installment_amount',
            field=models.DecimalField(decimal_places=30, default=1, max_digits=42, verbose_name='Installment Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='installment_start',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Installments'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='recurrence',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='monthly', max_length=10, verbose_name='Recurrence'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='reference_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reference Date'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transactions.transactiontag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default='IN', max_length=10, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='number_of_installments',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Installments'),
        ),
    ]
