# Generated by Django 5.1.2 on 2024-10-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='reference_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reference Date'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='recurrence_interval',
            field=models.PositiveIntegerField(verbose_name='Recurrence Interval'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='recurrence_type',
            field=models.CharField(choices=[('day', 'day(s)'), ('week', 'week(s)'), ('month', 'month(s)'), ('year', 'year(s)')], max_length=7, verbose_name='Recurrence Type'),
        ),
    ]
