# Generated by Django 5.1.2 on 2024-10-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_recurringtransaction_last_generated_reference_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='paused',
            field=models.BooleanField(default=False, verbose_name='Paused'),
        ),
    ]
