# Generated by Django 5.1.2 on 2024-10-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_recurringtransaction_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
