# Generated by Django 5.1.2 on 2024-11-02 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_archived_account_is_archived_and_more'),
        ('transactions', '0020_installmentplan_notes_recurringtransaction_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account', verbose_name='Account'),
        ),
    ]
