# Generated by Django 5.1.2 on 2024-11-05 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_transaction_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='paused',
            new_name='is_paused',
        ),
    ]
