# Generated by Django 5.1.3 on 2024-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_rename_paused_recurringtransaction_is_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'db_table': 'entities',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='entities',
            field=models.ManyToManyField(blank=True, help_text='Payees/Payers involved in this transaction', related_name='transactions', to='transactions.transactionentity', verbose_name='Entities'),
        ),
    ]
