# Generated by Django 5.1.3 on 2024-11-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_transactionentity_transaction_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='entities',
            field=models.ManyToManyField(blank=True, to='transactions.transactionentity', verbose_name='Entities'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='entities',
            field=models.ManyToManyField(blank=True, to='transactions.transactionentity', verbose_name='Entities'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='transactions.transactionentity', verbose_name='Entities'),
        ),
    ]
