# Generated by Django 5.1.3 on 2025-01-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_installmentplan_entities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='active',
            field=models.BooleanField(default=True, help_text="Deactivated categories won't be able to be selected when creating new transactions", verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='transactiontag',
            name='active',
            field=models.BooleanField(default=True, help_text="Deactivated tags won't be able to be selected when creating new transactions", verbose_name='Active'),
        ),
    ]
