# Generated by Django 5.1.3 on 2025-01-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_transactioncategory_active_transactiontag_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionentity',
            name='active',
            field=models.BooleanField(default=True, help_text="Deactivated entities won't be able to be selected when creating new transactions", verbose_name='Active'),
        ),
    ]
