# Generated by Django 5.1.5 on 2025-01-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_alter_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='Internal Note'),
        ),
    ]
