# Generated by Django 5.1.5 on 2025-01-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_transaction_internal_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_manager_name': 'objects', 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
