# Generated by Django 5.1.5 on 2025-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_transaction_deleted_transaction_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
    ]
