# Generated by Django 5.1.5 on 2025-01-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0032_transaction_created_at_transaction_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="internal_id",
            field=models.TextField(
                blank=True, null=True, unique=True, verbose_name="Internal ID"
            ),
        ),
    ]
