# Generated by Django 5.1.6 on 2025-03-05 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_alter_installmentplan_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionentity',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='transactiontag',
            unique_together={('owner', 'name')},
        ),
    ]
