# Generated by Django 5.1.6 on 2025-03-06 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_alter_transactioncategory_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transactioncategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='transactionentity',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='transactiontag',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='transactionentity',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionentity',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='transactiontag',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiontag',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionentity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
