# Generated by Django 5.1.6 on 2025-03-07 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_transaction_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='internal_id',
            field=models.TextField(blank=True, null=True, verbose_name='Internal ID'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('owner', 'internal_id')},
        ),
    ]
