# Generated by Django 5.1.6 on 2025-03-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_alter_transaction_internal_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='internal_id',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Internal ID'),
        ),
    ]
