# Generated by Django 5.1.7 on 2025-03-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_installmentplan_add_description_to_transaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Transaction Category', 'verbose_name_plural': 'Transaction Categories'},
        ),
        migrations.AlterModelOptions(
            name='transactionentity',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='transactiontag',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Transaction Tags', 'verbose_name_plural': 'Transaction Tags'},
        ),
    ]
