# Generated by Django 5.1.11 on 2025-06-20 04:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_quicktransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quicktransaction',
            unique_together={('name', 'owner')},
        ),
    ]
