# Generated by Django 5.1.11 on 2025-07-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_alter_quicktransaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mute',
            field=models.BooleanField(default=False, verbose_name='Mute'),
        ),
    ]
