# Generated by Django 5.1.11 on 2025-07-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_transaction_mute'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktransaction',
            name='mute',
            field=models.BooleanField(default=False, verbose_name='Mute'),
        ),
    ]
