from django.urls import path
import apps.transactions.views as views

urlpatterns = [
    path("transactions/", views.transaction_all_index, name="transactions_all_index"),
    path(
        "transactions/list/", views.transaction_all_list, name="transactions_all_list"
    ),
    path(
        "transactions/summary/",
        views.transaction_all_summary,
        name="transactions_all_summary",
    ),
    path(
        "transactions/actions/pay",
        views.bulk_pay_transactions,
        name="transactions_bulk_pay",
    ),
    path(
        "transactions/actions/unpay/",
        views.bulk_unpay_transactions,
        name="transactions_bulk_unpay",
    ),
    path(
        "transactions/actions/delete/",
        views.bulk_delete_transactions,
        name="transactions_bulk_delete",
    ),
    path(
        "transaction/<int:transaction_id>/pay",
        views.transaction_pay,
        name="transaction_pay",
    ),
    path(
        "transaction/<int:transaction_id>/delete",
        views.transaction_delete,
        name="transaction_delete",
    ),
    path(
        "transaction/<int:transaction_id>/edit",
        views.transaction_edit,
        name="transaction_edit",
    ),
    path(
        "transaction/add",
        views.transaction_add,
        name="transaction_add",
    ),
    path(
        "transactions/transfer",
        views.transactions_transfer,
        name="transactions_transfer",
    ),
    path("tags/", views.tags_index, name="tags_index"),
    path("tags/list/", views.tags_list, name="tags_list"),
    path("tags/table/active/", views.tags_table_active, name="tags_table_active"),
    path("tags/table/archived/", views.tags_table_archived, name="tags_table_archived"),
    path("tags/add/", views.tag_add, name="tag_add"),
    path(
        "tags/<int:tag_id>/edit/",
        views.tag_edit,
        name="tag_edit",
    ),
    path(
        "tags/<int:tag_id>/delete/",
        views.tag_delete,
        name="tag_delete",
    ),
    path("entities/", views.entities_index, name="entities_index"),
    path("entities/list/", views.entities_list, name="entities_list"),
    path(
        "entities/table/active/",
        views.entities_table_active,
        name="entities_table_active",
    ),
    path(
        "entities/table/archived/",
        views.entities_table_archived,
        name="entities_table_archived",
    ),
    path("entities/add/", views.entity_add, name="entity_add"),
    path(
        "entities/<int:entity_id>/edit/",
        views.entity_edit,
        name="entity_edit",
    ),
    path(
        "entities/<int:entity_id>/delete/",
        views.entity_delete,
        name="entity_delete",
    ),
    path("categories/", views.categories_index, name="categories_index"),
    path("categories/list/", views.categories_list, name="categories_list"),
    path(
        "categories/table/active/",
        views.categories_table_active,
        name="categories_table_active",
    ),
    path(
        "categories/table/archived/",
        views.categories_table_archived,
        name="categories_table_archived",
    ),
    path("categories/add/", views.category_add, name="category_add"),
    path(
        "categories/<int:category_id>/edit/",
        views.category_edit,
        name="category_edit",
    ),
    path(
        "categories/<int:category_id>/delete/",
        views.category_delete,
        name="category_delete",
    ),
    path(
        "installment-plans/",
        views.installment_plans_index,
        name="installment_plans_index",
    ),
    path(
        "installment-plans/list/",
        views.installment_plans_list,
        name="installment_plans_list",
    ),
    path(
        "installment-plans/list/active/",
        views.active_installment_plans_list,
        name="active_installment_plans_list",
    ),
    path(
        "installment-plans/list/finished/",
        views.finished_installment_plans_list,
        name="finished_installment_plans_list",
    ),
    path(
        "installment-plans/add/",
        views.installment_plan_add,
        name="installment_plan_add",
    ),
    path(
        "installment-plans/<int:installment_plan_id>/transactions/",
        views.installment_plan_transactions,
        name="installment_plan_transactions",
    ),
    path(
        "installment-plans/<int:installment_plan_id>/edit/",
        views.installment_plan_edit,
        name="installment_plan_edit",
    ),
    path(
        "installment-plans/<int:installment_plan_id>/delete/",
        views.installment_plan_delete,
        name="installment_plan_delete",
    ),
    path(
        "installment-plans/<int:installment_plan_id>/refresh/",
        views.installment_plan_refresh,
        name="installment_plan_refresh",
    ),
    path(
        "recurring-trasanctions/",
        views.recurring_transactions_index,
        name="recurring_trasanctions_index",
    ),
    path(
        "recurring-trasanctions/list/",
        views.recurring_transactions_list,
        name="recurring_transaction_list",
    ),
    path(
        "recurring-trasanctions/list/active/",
        views.active_recurring_transactions_list,
        name="active_recurring_transaction_list",
    ),
    path(
        "recurring-trasanctions/list/paused/",
        views.paused_recurring_transactions_list,
        name="paused_recurring_transaction_list",
    ),
    path(
        "recurring-trasanctions/list/finished/",
        views.finished_recurring_transactions_list,
        name="finished_recurring_transaction_list",
    ),
    path(
        "recurring-transactions/add/",
        views.recurring_transaction_add,
        name="recurring_transaction_add",
    ),
    path(
        "recurring-transactions/<int:recurring_transaction_id>/transactions/",
        views.recurring_transaction_transactions,
        name="recurring_transaction_transactions",
    ),
    path(
        "recurring-transactions/<int:recurring_transaction_id>/edit/",
        views.recurring_transaction_edit,
        name="recurring_transaction_edit",
    ),
    path(
        "recurring-transactions/<int:recurring_transaction_id>/delete/",
        views.recurring_transaction_delete,
        name="recurring_transaction_delete",
    ),
    path(
        "recurring-transactions/<int:recurring_transaction_id>/toggle-pause/",
        views.recurring_transaction_toggle_pause,
        name="recurring_transaction_toggle_pause",
    ),
    path(
        "recurring-transactions/<int:recurring_transaction_id>/finish/",
        views.recurring_transaction_finish,
        name="recurring_transaction_finish",
    ),
]
