# Generated by Django 5.1.5 on 2025-01-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='importprofile',
            name='yaml_config',
            field=models.TextField(verbose_name='YAML Configuration'),
        ),
    ]
