# Generated by Django 5.1.1 on 2024-09-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='currency',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, verbose_name='Suffix'),
        ),
    ]
