# Generated by Django 5.1.1 on 2024-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0004_exchangerate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Currency Name"
            ),
        ),
    ]
