# Generated by Django 5.1.2 on 2024-11-09 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_alter_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='exchange_currency',
            field=models.ForeignKey(blank=True, help_text='Default currency for exchange calculations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_currencies', to='currencies.currency', verbose_name='Exchange Currency'),
        ),
    ]
