# Generated by Django 5.1.5 on 2025-02-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0009_alter_exchangerateservice_target_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Currency Code'),
        ),
    ]
