# Generated by Django 5.1.5 on 2025-02-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0010_alter_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerateservice',
            name='fetch_interval_hours',
        ),
        migrations.AddField(
            model_name='exchangerateservice',
            name='fetch_interval',
            field=models.CharField(default='24', max_length=1000, verbose_name='Interval'),
        ),
        migrations.AddField(
            model_name='exchangerateservice',
            name='interval_type',
            field=models.CharField(choices=[('on', 'On'), ('every', 'Every X hours'), ('not_on', 'Not on')], default='every', max_length=255, verbose_name='Interval Type'),
        ),
        migrations.AlterField(
            model_name='exchangerateservice',
            name='service_type',
            field=models.CharField(choices=[('synth_finance', 'Synth Finance'), ('coingecko_free', 'CoinGecko (Demo/Free)'), ('coingecko_pro', 'CoinGecko (Pro)')], max_length=255, verbose_name='Service Type'),
        ),
    ]
