# Generated by Django 5.1.6 on 2025-03-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0011_remove_exchangerateservice_fetch_interval_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerateservice',
            name='service_type',
            field=models.CharField(choices=[('synth_finance', 'Synth Finance'), ('synth_finance_stock', 'Synth Finance Stock'), ('coingecko_free', 'CoinGecko (Demo/Free)'), ('coingecko_pro', 'CoinGecko (Pro)')], max_length=255, verbose_name='Service Type'),
        ),
    ]
