# Generated by Django 5.1.7 on 2025-03-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0013_alter_exchangerateservice_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
