# Generated by Django 5.2.15 on 2026-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0023_add_failure_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerateservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("coingecko_free", "CoinGecko (Demo/Free)"),
                    ("coingecko_pro", "CoinGecko (Pro)"),
                    ("transitive", "Transitive (Calculated from Existing Rates)"),
                    ("frankfurter", "Frankfurter"),
                    ("twelvedata", "TwelveData"),
                    ("twelvedatamarkets", "TwelveData Markets"),
                    ("yfinance", "Yahoo Finance"),
                ],
                max_length=255,
                verbose_name="Service Type",
            ),
        ),
    ]
