# Generated by Django 5.2.17 on 2026-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0024_alter_exchangerateservice_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerateservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("coingecko_free", "CoinGecko (Demo/Free)"),
                    ("coingecko_pro", "CoinGecko (Pro)"),
                    ("transitive", "Transitive (Calculated from Existing Rates)"),
                    ("frankfurter", "Frankfurter"),
                    ("twelvedata", "TwelveData"),
                    ("twelvedatamarkets", "TwelveData Markets"),
                    ("yfinance", "Yahoo Finance"),
                    ("fxmacrodata", "FXMacroData"),
                ],
                max_length=255,
                verbose_name="Service Type",
            ),
        ),
    ]
