# Generated by Django 5.1.2 on 2024-10-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_transactionrule_active_transactionrule_on_create_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionruleaction',
            unique_together={('rule', 'field')},
        ),
    ]
