# Generated by Django 5.1.3 on 2024-12-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_alter_transactionruleaction_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionruleaction',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_actions', to='rules.transactionrule', verbose_name='Rule'),
        ),
    ]
