# Generated by Django 5.1.5 on 2025-02-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_alter_updateorcreatetransactionruleaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateorcreatetransactionruleaction',
            name='search_entities',
            field=models.TextField(blank=True, help_text='Expression to match transaction entities (list of IDs or names)', verbose_name='Search Entities'),
        ),
        migrations.AddField(
            model_name='updateorcreatetransactionruleaction',
            name='search_entities_operator',
            field=models.CharField(choices=[('exact', 'is exactly'), ('contains', 'contains'), ('startswith', 'starts with'), ('endswith', 'ends with'), ('eq', 'equals'), ('gt', 'greater than'), ('lt', 'less than'), ('gte', 'greater than or equal'), ('lte', 'less than or equal')], default='contains', max_length=10, verbose_name='Entities Operator'),
        ),
        migrations.AddField(
            model_name='updateorcreatetransactionruleaction',
            name='search_tags',
            field=models.TextField(blank=True, help_text='Expression to match transaction tags (list of IDs or names)', verbose_name='Search Tags'),
        ),
        migrations.AddField(
            model_name='updateorcreatetransactionruleaction',
            name='search_tags_operator',
            field=models.CharField(choices=[('exact', 'is exactly'), ('contains', 'contains'), ('startswith', 'starts with'), ('endswith', 'ends with'), ('eq', 'equals'), ('gt', 'greater than'), ('lt', 'less than'), ('gte', 'greater than or equal'), ('lte', 'less than or equal')], default='contains', max_length=10, verbose_name='Tags Operator'),
        ),
    ]
