# Generated by Django 5.1.5 on 2025-02-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_updateorcreatetransactionruleaction_search_entities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionrule',
            options={'verbose_name': 'Transaction rule', 'verbose_name_plural': 'Transaction rules'},
        ),
        migrations.AlterModelOptions(
            name='transactionruleaction',
            options={'verbose_name': 'Edit transaction action', 'verbose_name_plural': 'Edit transaction actions'},
        ),
        migrations.AlterModelOptions(
            name='updateorcreatetransactionruleaction',
            options={'verbose_name': 'Update or create transaction action', 'verbose_name_plural': 'Update or create transaction actions'},
        ),
    ]
