# Generated by Django 5.1.6 on 2025-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_alter_transactionrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_account',
            field=models.TextField(blank=True, verbose_name='Search Account'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_amount',
            field=models.TextField(blank=True, verbose_name='Search Amount'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_category',
            field=models.TextField(blank=True, verbose_name='Search Category'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_description',
            field=models.TextField(blank=True, verbose_name='Search Description'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_entities',
            field=models.TextField(blank=True, verbose_name='Search Entities'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_internal_id',
            field=models.TextField(blank=True, verbose_name='Search Internal ID'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_internal_note',
            field=models.TextField(blank=True, verbose_name='Search Internal Note'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_is_paid',
            field=models.TextField(blank=True, verbose_name='Search Is Paid'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_notes',
            field=models.TextField(blank=True, verbose_name='Search Notes'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_reference_date',
            field=models.TextField(blank=True, verbose_name='Search Reference Date'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_tags',
            field=models.TextField(blank=True, verbose_name='Search Tags'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='search_type',
            field=models.TextField(blank=True, verbose_name='Search Type'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_account',
            field=models.TextField(blank=True, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_amount',
            field=models.TextField(blank=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_category',
            field=models.TextField(blank=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_date',
            field=models.TextField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_entities',
            field=models.TextField(blank=True, verbose_name='Entities'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_internal_id',
            field=models.TextField(blank=True, verbose_name='Internal ID'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_internal_note',
            field=models.TextField(blank=True, verbose_name='Internal Note'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_is_paid',
            field=models.TextField(blank=True, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_reference_date',
            field=models.TextField(blank=True, verbose_name='Reference Date'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_tags',
            field=models.TextField(blank=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_type',
            field=models.TextField(blank=True, verbose_name='Type'),
        ),
    ]
