# Generated by Django 5.1.6 on 2025-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_alter_updateorcreatetransactionruleaction_search_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorcreatetransactionruleaction',
            name='set_is_paid',
            field=models.TextField(blank=True, verbose_name='Paid'),
        ),
    ]
