# Generated by Django 5.1.7 on 2025-03-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0012_transactionrule_owner_transactionrule_shared_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrule',
            name='on_delete',
            field=models.BooleanField(default=False),
        ),
    ]
