#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py loaddata ./fixtures/*.json
#python manage.py compilemessages
exec python manage.py runserver 0.0.0.0:8000
